# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14bcd12452dda2fb924bdcac61d7e071c8215cd4ec5ad65fed4011e12f1170bd14ff2e5733b9715526e5a3b5cdddcafa5980f2b37e0e1e6cc6fd388ecee8031a

test:
  secret_key_base: cd52d3a8765fddef17790e4a246a17b1d1a5d8ec92ad865d68e334add90648e8e27226a3534a029e6daf94d83f28a5d0af90768a94adc560e9219129dd9c16b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
